### ISSUE TITLE
Issue about building environment

### ISSUE THREAD

**Issue by Zuricho** [barbireau/HVQE#1]
Hi,
I failed to build the python environment by yml, could you offer a list of packages needed for installation?

**Comment by barbireau** [comment]
Hi Zuricho, 

Which platform are you on? I only tested the installation myself on UNIX platforms, but would be glad to help you with installation on Windows also. 

The .yml files are themselves simply lists of packages. To see the packages, just open the .yml files in a text editor, or even just on github:
If you have have a CUDA-enabled GPU:
https://github.com/barbireau/HVQE/blob/main/environment/environment_GPU.yml 
If not:
https://github.com/barbireau/HVQE/blob/main/environment/environment_no_GPU.yml

**Comment by Zuricho** [comment]
Actually I'm on Windows but I can try on Linux. I understand that the yml file contains the packages, but that is too much of them. I'm considering install them one by one to find which one made me failed to build the environment

**Comment by barbireau** [comment]
Let me know if you encounter are any issues on Linux...

**Comment by Zuricho** [comment]
I succeed on Linux, thanks!

**Comment by barbireau** [comment]
Great! I will add a remark in the README.md that the installation has only been tested on UNIX systems. I may extend this to Windows systems if there is any demand.

**Comment by barbireau** [comment]
(Please contact me if you need any other help!)
